#builds and runs tests
name: UdpToHttpGateway build
on:
  push:
    branches:
        - main 
    tags:
        - v*
  pull_request:
    branches:
        - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: user/app:test
  SOURCE_DATE_EPOCH: 0

jobs:
  docker:
    #some links about the approaches used
    # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
    # https://docs.docker.com/build/ci/github-actions/test-before-push/
    # https://docs.docker.com/build/ci/github-actions/export-docker/
    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
    # https://docs.docker.com/build/ci/github-actions/reproducible-builds/
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db #3.6.1
      - name: Login to Container registry Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and export to docker
        id: push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 #v6.7.0
        with:
          context: "./UdpToHttpGateway"
          file: "./UdpToHttpGateway/UdpToHttpGateway/Dockerfile"
          load: true
          tags: ${{ env.TEST_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup .NET (for the test)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Test
        working-directory: "./UdpToHttpGateway/UdpToHttpGateway.Tests"
        run: |
            docker run --rm ${{ env.TEST_TAG }} -p 0.0.0.0:4280:4280/udp --add-host=host.docker.internal:172.17.0.1&
            # docker run --rm ${{ env.TEST_TAG }} --network "host"&
            #TODO: we might want a pause before moving forward below ... also run the app with debug conf to get more info
            dotnet test -c Release --blame --blame-hang --blame-hang-timeout 10min
      - name: Build and push
        id: buildandpush
        # if: ${{ startswith(github.ref, 'refs/tags')}} # only push tags? startswith(github.ref, 'refs/tags')
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 #v6.7.0
        with:
          platforms: linux/amd64,linux/arm64
          context: "./UdpToHttpGateway"
          file: "./UdpToHttpGateway/UdpToHttpGateway/Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c #v1.4.3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.buildandpush.outputs.digest }}
          push-to-registry: true
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}